### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by alexchan378** [Sorrow446/Sony-Kuke-Downloader#1]
HI,

I have install the DL, but showing below error message, may i ask what I can set up property?

****
Downloading track 1 of 8: Finding Home (from Suite for Strings) - 24-bit / 96 kHz FLAC
Segment 1 of 63.Failed to download segments.
403 Forbidden
Downloading track 2 of 8: Air (For Flute and Piano) - 24-bit / 96 kHz FLAC
Segment 1 of 163.Failed to download segments.
403 Forbidden
Downloading track 3 of 8: A Time of Uncertainties (From "Three Orchestral Essays") - 24-bit / 96 kHz FLAC
Segment 1 of 86.Failed to download segments.

**Comment by Sorrow446** [comment]
Fixed a week ago. https://github.com/Sorrow446/Sony-Kuke-Downloader/commit/f7306f95f24ed3e9b34f5088fe33762296bd864e
Need to run from source instead of the outdated binary.
