### ISSUE TITLE
can't find sonyselectid

### ISSUE THREAD

**Issue by evafans** [Sorrow446/Sony-Kuke-Downloader#2]
I logged in, but I can't find  anything that looks like sonyselectid.
![QQ截图20220621181647](https://user-images.githubusercontent.com/88836421/174777384-0af6f9e2-340e-4ede-841e-adc71f768f08.png)

![QQ截图20220621181710](https://user-images.githubusercontent.com/88836421/174777430-fae4d4ff-3157-4da5-ac7f-9b19ba5aae08.png)

**Comment by Sorrow446** [comment]
Could you send me your credentials so I can look into it?
https://www.reddit.com/user/Sorrow446/
Sorrow#6826

**Comment by Sorrow446** [comment]
It's stored as a cookie now instead, updated repo.
